### ISSUE TITLE
The maximum number of addresses has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: AddressLimitExceed ed; Request ID: 6d989896-09a5-4ea8-b492-23949e897a47; Proxy: null)

### ISSUE THREAD

**Issue by cwulfman** [TrustTheVote-Project/Electorate-Vanadium-Ledger#11]
```bash
cliff:~/environment/Electorate-Vanadium-Ledger/src (source) $ cdk deploy InterfaceStack
This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

Security Group Changes
┌───┬─────────────────────────────────────────────┬─────┬────────────┬──────────────────────┐
│   │ Group                                       │ Dir │ Protocol   │ Peer                 │
├───┼─────────────────────────────────────────────┼─────┼────────────┼──────────────────────┤
│ - │ ${DefaultVpcEndpoint/SecurityGroup.GroupId} │ In  │ Everything │ sg-082bdc23fc2710307 │
├───┼─────────────────────────────────────────────┼─────┼────────────┼──────────────────────┤
│ + │ ${DefaultVpcEndpoint/SecurityGroup.GroupId} │ In  │ Everything │ sg-0e966bb91772c4264 │
└───┴─────────────────────────────────────────────┴─────┴────────────┴──────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
InterfaceStack: deploying...
[0%] start: Publishing 959bd938610d7621a5e903ec4c7bf380e90f2139562284b6f4c8ec3c04dc39ad:current
[33%] success: Published 959bd938610d7621a5e903ec4c7bf380e90f2139562284b6f4c8ec3c04dc39ad:current
[33%] start: Publishing 7e5b454ac1d3e811ca1eaff67c7d11eeafed4f0a3f3a78987f0f0998e9d8555b:current
[66%] success: Published 7e5b454ac1d3e811ca1eaff67c7d11eeafed4f0a3f3a78987f0f0998e9d8555b:current
[66%] start: Publishing 44460275068046d09a39aa78c1ee195ae851945f7f6a113562a28899f255c29c:current
[100%] success: Published 44460275068046d09a39aa78c1ee195ae851945f7f6a113562a28899f255c29c:current
InterfaceStack: creating CloudFormation changeset...
8:22:15 PM | CREATE_FAILED        | AWS::EC2::EIP                         | LedgerVpcPublicSubnet3EIP594B364D
The maximum number of addresses has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: AddressLimitExceed
ed; Request ID: 6d989896-09a5-4ea8-b492-23949e897a47; Proxy: null)

        PublicSubnet.addNatGateway (/home/ec2-user/environment/Electorate-Vanadium-Ledger/src/node_modules/@aws-cdk/aws-ec2/lib PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | InterfaceStack
/vpc.ts:1214:21)
        \_ NatGatewayProvider.configureNat (/home/ec2-user/environment/Electorate-Vanadium-Ledger/src/node_modules/@aws-cdk/awsVpcEndpointSecurityGroup2F355145, ApiCloudWatchRole73EC6FC4, LedgerVpcPublicSubnet1EIP6A3FB6D2, CDKMetadata, Led
-ec2/lib/nat.ts:116:27)
        \_ Vpc.createNatGateways (/home/ec2-user/environment/Electorate-Vanadium-Ledger/src/node_modules/@aws-cdk/aws-ec2/lib/v
pc.ts:887:14)
        \_ new Vpc (/home/ec2-user/environment/Electorate-Vanadium-Ledger/src/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:817:14)
        \_ new InterfaceStack (/home/ec2-user/environment/Electorate-Vanadium-Ledger/src/stacks/interface-stack.ts:22:23)
        \_ Object.<anonymous> (/home/ec2-user/environment/Electorate-Vanadium-Ledger/src/bin/document-ledger.ts:19:1)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Module.m._compile (/home/ec2-user/environment/Electorate-Vanadium-Ledger/src/node_modules/ts-node/src/index.ts:1043:
23)
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Object.require.extensions.<computed> [as .ts] (/home/ec2-user/environment/Electorate-Vanadium-Ledger/src/node_module
s/ts-node/src/index.ts:1046:12)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ main (/home/ec2-user/environment/Electorate-Vanadium-Ledger/src/node_modules/ts-node/src/bin.ts:225:14)
        \_ Object.<anonymous> (/home/ec2-user/environment/Electorate-Vanadium-Ledger/src/node_modules/ts-node/src/bin.ts:512:3)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ node:internal/main/run_main_module:17:47


 ❌  InterfaceStack failed: Error: The stack named InterfaceStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/home/ec2-user/.nvm/versions/node/v16.13.0/lib/node_modules/cdk/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/home/ec2-user/.nvm/versions/node/v16.13.0/lib/node_modules/cdk/node_modules/aws-cdk/lib/api/deploy-stack.ts:337:26)
    at CdkToolkit.deploy (/home/ec2-user/.nvm/versions/node/v16.13.0/lib/node_modules/cdk/node_modules/aws-cdk/lib/cdk-toolkit.ts:194:24)
    at initCommandLine (/home/ec2-user/.nvm/versions/node/v16.13.0/lib/node_modules/cdk/node_modules/aws-cdk/bin/cdk.ts:267:9)
The stack named InterfaceStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

**Comment by immibis** [comment]
Seems like you reached your EIP limit

**Comment by cwulfman** [comment]
This was resolved.
